- hosts: all
  vars:
    loop_1: "hello1"
  tasks:
  - name: Prepare Array for ArrayList
    set_fact:
      ArrayList: []
      
  - name: Ansible loop with conditional example
    debug:
      msg: "{{ item }}"
    set_fact:
    my_joined_list: "{{ item | join('\n') }}"
    ArrayList: "{{ ArrayList }} + [ '{{ item }}' ]"
    with_items:
      - "hello1"
      - "hello2"
      - "hello3"
      - "hello1"
    when: item == "{{ loop_1 }}"
  - name: Ansible loop with conditional example
    debug:
      msg: Message- "{{ my_joined_list }}"
