- hosts: all
  vars:
    loop_1: "hello1"
  tasks:
  - name: Prepare Array for ArrayList
    set_fact:
      ArrayList: []
  - name: Ansible  
    set_fact:
      ArrayList: "{{ ArrayList }} + [ '{{ item }}' ]"
    with_items:
      - "hello1"
      - "hello2"
      - "hello3"
      - "hello5"
    when: (item == "{{ loop_1 }}" or item == "hello5")

        
  - name: Examine the joined string
    debug:
        msg: "My Values - {{ ArrayList | length }}"
        
