- hosts: all
  vars:
    loop_1: "hello1"
  tasks:
  - name: Prepare Array for ArrayList
    set_fact:
      ArrayList: []
      
  - name: Ansible loop with conditional example
    set_fact:
        my_joined_list: "{{ item | join(', ') }}"
    with_items:
      - "hello1"
      - "hello2"
      - "hello3"
      - "hello1"
    when: item == "{{ loop_1 }}"

        
  - name: Examine the joined string
    debug:
        msg: "{{ my_joined_list }}"
