- hosts: all
  vars:
    loop_1: "hello1"
  tasks:
  - name: Prepare Array for ArrayList
    set_fact:
      ArrayList: []
      
  - name: Prepare Array for ArrayList1
    set_fact:
      ArrayList1: []
    
  - name: Ansible loop with conditional example
    set_fact:
      ArrayList: "{{ ArrayList }} + [ '{{ item }}' ]"    
    with_items:
      - "hello1"
      - "hello2"
      - "hello3"
      - "hello5"
    when: (item == "{{ loop_1 }}" or item == "hello5")

        
  - name: Examine the joined string
    debug:
        msg: "My Values - {{ ArrayList | join(',') }}"
        
  - name: Create a VM with a custom image
    azure_rm_resourcegroup_facts:
      ArrayList1: "{{ ArrayList1 }} + [ '{{ item }}' ]"
    azure_rm_virtualmachine:
      resource_group: Testing
      name: testvm001
    with_items:
      - "hello1"
      - "hello2"
      - "hello3"
      - "hello5"
    when: (item == "{{ loop_1 }}" or item == "hello5")
    
  - name: Examine the joined string azure_rm_resourcegroup_facts
    debug:
        msg: "My Values - {{ ArrayList1 | join(',') }}"
    
